# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7db5d0e1684e956fc12a694393b97c69ba4fd44cfadb7cbb7a15be5990c97d3f1f626dbef735840840575c7b2462f48509c4e5b2da3aedadd3f3b01d4b8c8540

test:
  secret_key_base: e52ceb27a448c5870747c9b1e0ee572bc998af9dc28d3ca0174bb9b5b82ba2edc56ad67ab1b1feb0e16d4091bf4dff8396cebc8dd0edecfbc67e1e22847a4301

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
